//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Insight.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.
        /// </summary>
        public static string Cache {
            get {
                return ResourceManager.GetString("Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Age.
        /// </summary>
        public static string CodeAge {
            get {
                return ResourceManager.GetString("CodeAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days since last modification.
        /// </summary>
        public static string CodeAge_Days {
            get {
                return ResourceManager.GetString("CodeAge_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Coupling.
        /// </summary>
        public static string Coupling {
            get {
                return ResourceManager.GetString("Coupling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagrams.
        /// </summary>
        public static string Diagrams {
            get {
                return ResourceManager.GetString("Diagrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory is not contained in the project base. This is not allowed!.
        /// </summary>
        public static string ErrorDirectoryNotInProjectBase {
            get {
                return ResourceManager.GetString("ErrorDirectoryNotInProjectBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extensions
        ///(Include).
        /// </summary>
        public static string FileExtensions {
            get {
                return ResourceManager.GetString("FileExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragmentation.
        /// </summary>
        public static string Fragmentation {
            get {
                return ResourceManager.GetString("Fragmentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future Hotspots.
        /// </summary>
        public static string FutureHotspots {
            get {
                return ResourceManager.GetString("FutureHotspots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotspots.
        /// </summary>
        public static string Hotspots {
            get {
                return ResourceManager.GetString("Hotspots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge.
        /// </summary>
        public static string Knowledge {
            get {
                return ResourceManager.GetString("Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Loss.
        /// </summary>
        public static string KnowledgeLoss {
            get {
                return ResourceManager.GetString("KnowledgeLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines of Code.
        /// </summary>
        public static string LinesOfCode {
            get {
                return ResourceManager.GetString("LinesOfCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines of Code.
        /// </summary>
        public static string LOC {
            get {
                return ResourceManager.GetString("LOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Commits.
        /// </summary>
        public static string NumberOfCommits {
            get {
                return ResourceManager.GetString("NumberOfCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths
        ///(Exclude).
        /// </summary>
        public static string PathsExclude {
            get {
                return ResourceManager.GetString("PathsExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths
        ///(Include).
        /// </summary>
        public static string PathsInclude {
            get {
                return ResourceManager.GetString("PathsInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictions.
        /// </summary>
        public static string Predictions {
            get {
                return ResourceManager.GetString("Predictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Base.
        /// </summary>
        public static string ProjectBase {
            get {
                return ResourceManager.GetString("ProjectBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project settings.
        /// </summary>
        public static string ProjectViewTitle {
            get {
                return ResourceManager.GetString("ProjectViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the developer for knowledge loss.
        /// </summary>
        public static string SelectDeveloper {
            get {
                return ResourceManager.GetString("SelectDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select developer.
        /// </summary>
        public static string SelectDeveloperTitle {
            get {
                return ResourceManager.GetString("SelectDeveloperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Control.
        /// </summary>
        public static string SourceControl {
            get {
                return ResourceManager.GetString("SourceControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Provider.
        /// </summary>
        public static string SourceProvider {
            get {
                return ResourceManager.GetString("SourceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to include the work related information?.
        /// </summary>
        public static string SyncIncludeContributions {
            get {
                return ResourceManager.GetString("SyncIncludeContributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync reads the version control&apos;s log and calculates metrics for all supported files. This takes time. 
        ///
        ///The data is persistently cached and used when doing the various analyses. 
        ///If you synced before all cached data is deleted and rebuild. 
        ///Best your repository is up to date and has no local changes.
        ///
        ///Do you want to proceed?.
        /// </summary>
        public static string SyncInstructions {
            get {
                return ResourceManager.GetString("SyncInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To clipboard.
        /// </summary>
        public static string ToClipboard {
            get {
                return ResourceManager.GetString("ToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend.
        /// </summary>
        public static string TrendViewTitle {
            get {
                return ResourceManager.GetString("TrendViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string UpdateCache {
            get {
                return ResourceManager.GetString("UpdateCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize.
        /// </summary>
        public static string Visualize {
            get {
                return ResourceManager.GetString("Visualize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragmentation.
        /// </summary>
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working ....
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workitem Regex.
        /// </summary>
        public static string WorkItemRegEx {
            get {
                return ResourceManager.GetString("WorkItemRegEx", resourceCulture);
            }
        }
    }
}
